[default]
exten => sipp,1,NoOp(Calling user sipp)
same => n,Dial(PJSIP/sipp)

exten => service,1,NoOp(Calling user service)
same => n,Dial(PJSIP/service)

exten => 1000,1,NoOp(Calling user 1000)
same => n,Dial(PJSIP/1000)

exten => 2000,1,NoOp(Calling user 2000)
same => n,Dial(PJSIP/2000)
