[general]
type=general
trace_on=enabled
trace_hep=enabled

[udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[service]
type=endpoint
transport=udp
context=default
disallow=all
allow=ulaw
auth=service
aors=service

[service]
type=auth
auth_type=userpass
username=service
password=service

[service]
type=aor
max_contacts=1
  
[sipp]
type=endpoint
transport=udp
context=default
disallow=all
allow=ulaw
aors=sipp
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
timers=no

[sipp]
type=aor
max_contacts=1
