[udp]
type=transport
protocol=udp
bind=192.168.10.188:5060

[service]
type=endpoint
transport=udp
context=default
disallow=all
allow=ulaw
auth=service-auth
aors=service-aors

[service-auth]
type=auth
auth_type=userpass
username=service
password=service

[service-aors]
type=aor
max_contacts=1
contact=sip:service@<server-ip-address>:<port>

[sipp]
type=endpoint
transport=udp
context=default
disallow=all
allow=ulaw
aors=sipp-aors
direct_media=no
force_rport=yes
rewrite_contact=yes

[sipp-aors]
type=aor
max_contacts=1
contact=sip:sipp@<client-ip-address>:<port>

[1000]
type=endpoint
transport=udp
context=default
disallow=all
allow=ulaw
auth=1000-auth
aors=1000-aors

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=1000

[1000-aors]
type=aor
max_contacts=2
